### PR TITLE
Feature/new structure

### PR DESCRIPTION
**Pull request by moonso**
- Fixed a better command line structure
- Added some dependencies
- svsim pipeline works

### CODE REVIEW

**Comment by mfranberg** [comment]
These changes should be made before I can merge this:
- The README.md should be updated to reflect the new interface.
- The svsim_pipeline should be able to pass options to other parts of the pipeline as before.

Also not that there are some other users for this tool now, so it might take some time before it is a good idea to merge this into master (develop is fine though).

**Comment by mfranberg** [comment]
Very nice initiative by the way :+1:

**Comment by moonso** [comment]
@fadern  "What is the purpose of this line? They should already be floats by the click definition."
No click reads them as strings when they come as a list. 
There might be a smarter way but this works for now.

**Comment by moonso** [comment]
@fadern fixed the issues in commit: https://github.com/fadern/svsim/commit/d95885cb7f7516a01a4e7f3074470104fc196e2c

**Comment by mfranberg** [comment]
Awesome!

**Pull request merged**
